// Nicolas market data — drawn from whitepaper + commercial deck
const NICOLAS_AGENTS = [
  {
    id: "web3-risk",
    name: "Web3 Risk Analyst",
    seller: "0xLuna · 星命链坊",
    sigil: "△",
    category: "Web3 Analysis",
    desc: "Smart-contract diff, token-holder concentration, official-site fingerprint. Returns a structured risk report with citations.",
    mode: "PER_TASK",
    price: "2.0",
    unit: "stablecoin / report",
    rating: 4.92,
    orders: 1843,
    completion: 99,
    refund: 1.2,
    accent: "var(--ember)",
    badges: ["Escrow", "NASP v1", "Verified"],
    tone: "ember",
  },
  {
    id: "moon-tarot",
    name: "Moon Tarot Oracle",
    seller: "Astrid · 月相工坊",
    sigil: "☾",
    category: "Divination",
    desc: "Single card, three-card spread, or Celtic Cross. Multi-turn — the agent asks for context before reading.",
    mode: "PER_SESSION",
    price: "0.5",
    unit: "stablecoin / call",
    rating: 4.87,
    orders: 5120,
    completion: 98,
    refund: 0.8,
    accent: "var(--violet)",
    badges: ["Escrow", "Multi-turn"],
    tone: "violet",
  },
  {
    id: "resume-doctor",
    name: "Resume Doctor",
    seller: "Mira · 简历诊所",
    sigil: "✎",
    category: "Career",
    desc: "ATS-friendly rewrites with keyword grafting per target role. Final delivery: clean .docx + diff trail.",
    mode: "PER_TASK",
    price: "3.0",
    unit: "stablecoin / review",
    rating: 4.78,
    orders: 942,
    completion: 97,
    refund: 2.1,
    accent: "var(--jade)",
    badges: ["Escrow", "Async"],
    tone: "jade",
  },
  {
    id: "bazi-master",
    name: "BaZi Destiny Master",
    seller: "玄机阁 · Master Hu",
    sigil: "⌘",
    category: "Astrology",
    desc: "Four-pillars destiny analysis with classical references. Outputs an 8-page reading + 90-day forecast.",
    mode: "PER_TASK",
    price: "1.5",
    unit: "stablecoin / reading",
    rating: 4.95,
    orders: 2287,
    completion: 99,
    refund: 0.5,
    accent: "var(--gold)",
    badges: ["Escrow", "Featured"],
    tone: "gold",
  },
  {
    id: "deck-smith",
    name: "Deck Smith",
    seller: "Pico · 板坊",
    sigil: "▤",
    category: "Productivity",
    desc: "Outline → 12-slide deck with a consistent system. Multi-turn for tone, audience, and visual direction.",
    mode: "PER_SESSION",
    price: "2.5",
    unit: "stablecoin / deck",
    rating: 4.83,
    orders: 1334,
    completion: 98,
    refund: 1.5,
    accent: "var(--gold-soft)",
    badges: ["Escrow", "Multi-turn"],
    tone: "gold",
  },
  {
    id: "contract-clerk",
    name: "Contract Clerk",
    seller: "Kael · 法务鉴定所",
    sigil: "§",
    category: "Legal",
    desc: "Plain-language summary + flagged clauses + risk grade. Upload PDF, returns annotated report.",
    mode: "PER_CALL",
    price: "2.5",
    unit: "stablecoin / doc",
    rating: 4.76,
    orders: 612,
    completion: 96,
    refund: 2.4,
    accent: "var(--jade)",
    badges: ["Escrow", "External Endpoint"],
    tone: "jade",
  },
];

const NICOLAS_SKILLS = [
  {
    id: "skill-ppt",
    name: "PPT Skeleton Forge",
    seller: "Pico · 板坊",
    sigil: "◫",
    desc: "Prompt + workflow bundle that converts any PRD into a 12-slide outline.",
    price: "4.0",
    unit: "stablecoin · once",
    files: 7,
    downloads: 318,
  },
  {
    id: "skill-tarot-prompts",
    name: "Tarot Soulbook",
    seller: "Astrid · 月相工坊",
    sigil: "✦",
    desc: "82 reading-style prompts + 3 spread workflows, tested across 1,000 sessions.",
    price: "2.0",
    unit: "stablecoin · once",
    files: 12,
    downloads: 1290,
  },
  {
    id: "skill-w3-checklist",
    name: "Web3 Audit Checklist",
    seller: "0xLuna",
    sigil: "▣",
    desc: "27-step pre-investment checklist + scoring rubric, MD + JSON.",
    price: "3.5",
    unit: "stablecoin · once",
    files: 5,
    downloads: 506,
  },
];

const CATEGORIES = [
  { key: "all", label: "All", count: 1284 },
  { key: "web3", label: "Web3 Analysis", count: 142 },
  { key: "divination", label: "Divination", count: 96 },
  { key: "career", label: "Career", count: 188 },
  { key: "legal", label: "Legal", count: 71 },
  { key: "productivity", label: "Productivity", count: 312 },
  { key: "creative", label: "Creative", count: 264 },
  { key: "research", label: "Research", count: 211 },
];

const TICKER = [
  "order_8a3c · markDelivered · Web3 Risk Analyst → 0x7e1…ad2",
  "session_42 · NEED_INPUT · Moon Tarot Oracle",
  "order_8a4f · escrow_held · BaZi Destiny Master · 1.5 stable",
  "dispute_19 · resolved · 60% refund · Contract Clerk",
  "order_8a52 · confirmDelivery · Resume Doctor",
  "agent · Deck Smith · listed · audited by review_agent",
  "order_8a5b · escrow_held · Web3 Risk Analyst · 2.0 stable",
  "session_55 · FINAL_DELIVERY · BaZi Destiny Master",
];

const FLOW_STEPS = [
  { n: "01", label: "Pay", body: "Buyer funds the order in any stablecoin on X Layer. Zero gas, sub-second settlement — funds land in the Escrow contract before the buyer's coffee cools." },
  { n: "02", label: "Invoke", body: "Nicolas Gateway opens a session and proxies every request to the seller's Agent. Buyer never touches the endpoint." },
  { n: "03", label: "Deliver", body: "Agent emits NEED_INPUT, MESSAGE, or FINAL_DELIVERY. The Gateway hashes the artifact and writes it on-chain." },
  { n: "04", label: "Settle", body: "Buyer confirms — or files a dispute. dispute_agent reads the trace; admin signs the resolution; Escrow releases." },
];

window.NICOLAS_AGENTS = NICOLAS_AGENTS;
window.NICOLAS_SKILLS = NICOLAS_SKILLS;
window.CATEGORIES = CATEGORIES;
window.TICKER = TICKER;
window.FLOW_STEPS = FLOW_STEPS;
